name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v2.0.0)'
        required: false
        default: 'dev'

permissions:
  contents: write

jobs:
  build-linux:
    name: Build Linux (${{ matrix.arch }})
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - arch: amd64
            goarch: amd64
            cc: gcc
          - arch: arm64
            goarch: arm64
            cc: aarch64-linux-gnu-gcc
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Set up cross-compilation for ARM64
        if: matrix.arch == 'arm64'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            # For ARM64 cross-compilation, install basic tools
            sudo apt-get install -y \
              gcc-aarch64-linux-gnu \
              pkg-config \
              libssl-dev
          else
            # For AMD64 native build
            sudo apt-get install -y \
              gcc \
              libgl1-mesa-dev \
              xorg-dev \
              libx11-dev \
              libxcursor-dev \
              libxrandr-dev \
              libxinerama-dev \
              libxi-dev \
              libxxf86vm-dev \
              libssl-dev \
              pkg-config \
              wkhtmltopdf
          fi

      - name: Install Go dependencies
        run: |
          go mod download
          go mod tidy

      - name: Build GUI for Linux
        env:
          CGO_ENABLED: 1
          GOOS: linux
          GOARCH: ${{ matrix.goarch }}
          CC: ${{ matrix.cc }}
        run: |
          go build -ldflags="-s -w" \
          -o build/ravro_dcrpt_gui-${{ matrix.arch }} \
          ./cmd/gui

      - name: Create tarball
        run: |
          cd build
          tar -czf ravro_dcrpt-linux-${{ matrix.arch }}.tar.gz ravro_dcrpt_gui-${{ matrix.arch }}
          cd ..

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.arch }}
          path: build/ravro_dcrpt-linux-${{ matrix.arch }}.tar.gz
          retention-days: 7

  build-macos:
    name: Build macOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-13
            arch: amd64
          - os: macos-latest
            arch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Install macOS dependencies
        run: |
          # Install OpenSSL
          if ! brew list openssl@3 &>/dev/null; then
            brew install openssl@3
          else
            echo "OpenSSL@3 is already installed"
          fi
          
          # Install wkhtmltopdf
          if ! command -v wkhtmltopdf &> /dev/null; then
            brew install --cask wkhtmltopdf || {
              echo "Cask install failed, trying direct download..."
              WKHTMLTOPDF_VERSION="0.12.6-1"
              DOWNLOAD_URL="https://github.com/wkhtmltopdf/packaging/releases/download/${WKHTMLTOPDF_VERSION}/wkhtmltox-${WKHTMLTOPDF_VERSION}.macos-cocoa.pkg"
              curl -L -o /tmp/wkhtmltox.pkg "$DOWNLOAD_URL"
              sudo installer -pkg /tmp/wkhtmltox.pkg -target /
              rm -f /tmp/wkhtmltox.pkg
            }
          fi

      - name: Set OpenSSL environment variables (Intel)
        if: matrix.arch == 'amd64'
        run: |
          OPENSSL_PREFIX="/usr/local/opt/openssl@3"
          echo "PKG_CONFIG_PATH=$OPENSSL_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "CGO_CFLAGS=-I$OPENSSL_PREFIX/include" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-L$OPENSSL_PREFIX/lib -lssl -lcrypto" >> $GITHUB_ENV

      - name: Set OpenSSL environment variables (Apple Silicon)
        if: matrix.arch == 'arm64'
        run: |
          OPENSSL_PREFIX="/opt/homebrew/opt/openssl@3"
          echo "PKG_CONFIG_PATH=$OPENSSL_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "CGO_CFLAGS=-I$OPENSSL_PREFIX/include" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-L$OPENSSL_PREFIX/lib -lssl -lcrypto" >> $GITHUB_ENV

      - name: Install Go dependencies
        run: |
          go mod download
          go mod tidy

      - name: Build GUI for macOS
        run: |
          CGO_ENABLED=1 \
          go build -ldflags="-s -w" \
          -o build/ravro_dcrpt_gui-${{ matrix.arch }} \
          ./cmd/gui

      - name: Create app bundle (for GUI)
        run: |
          mkdir -p "build/Ravro Decryption Tool.app/Contents/MacOS"
          mkdir -p "build/Ravro Decryption Tool.app/Contents/Resources"
          
          cp build/ravro_dcrpt_gui-${{ matrix.arch }} "build/Ravro Decryption Tool.app/Contents/MacOS/ravro_dcrpt_gui"
          
          # Create Info.plist
          cat > "build/Ravro Decryption Tool.app/Contents/Info.plist" << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleExecutable</key>
              <string>ravro_dcrpt_gui</string>
              <key>CFBundleIdentifier</key>
              <string>com.ravro.decryption</string>
              <key>CFBundleName</key>
              <string>Ravro Decryption Tool</string>
              <key>CFBundlePackageType</key>
              <string>APPL</string>
              <key>CFBundleShortVersionString</key>
              <string>2.0.0</string>
              <key>CFBundleVersion</key>
              <string>1</string>
              <key>LSMinimumSystemVersion</key>
              <string>11.0</string>
              <key>NSHighResolutionCapable</key>
              <true/>
          </dict>
          </plist>
          EOF

      - name: Create tarball
        run: |
          cd build
          tar -czf ravro_dcrpt-darwin-${{ matrix.arch }}.tar.gz \
            "Ravro Decryption Tool.app"
          cd ..

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.arch }}
          path: build/ravro_dcrpt-darwin-${{ matrix.arch }}.tar.gz
          retention-days: 7

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Install Windows dependencies
        shell: powershell
        run: |
          # Install wkhtmltopdf
          choco install -y wkhtmltopdf
          
          # Install OpenSSL (64-bit only)
          Write-Host "Installing OpenSSL via Chocolatey..."
          choco install -y openssl
          
          # Check common installation paths
          $OPENSSL_PATHS = @(
            "C:\Program Files\OpenSSL-Win64",
            "C:\Program Files\OpenSSL",
            "C:\OpenSSL-Win64",
            "C:\OpenSSL"
          )
          
          $OPENSSL_FOUND = $false
          $ACTUAL_OPENSSL_DIR = ""
          
          foreach ($path in $OPENSSL_PATHS) {
            if (Test-Path $path) {
              Write-Host "✅ Found OpenSSL at: $path"
              $ACTUAL_OPENSSL_DIR = $path
              $OPENSSL_FOUND = $true
              break
            }
          }
          
          if (-not $OPENSSL_FOUND) {
            Write-Host "Searching for OpenSSL in Program Files..."
            $found = Get-ChildItem "C:\Program Files" -Directory -Filter "*OpenSSL*" -ErrorAction SilentlyContinue | Select-Object -First 1
            if ($found) {
              $ACTUAL_OPENSSL_DIR = $found.FullName
              Write-Host "✅ Found OpenSSL at: $ACTUAL_OPENSSL_DIR"
              $OPENSSL_FOUND = $true
            }
          }
          
          if (-not $OPENSSL_FOUND) {
            Write-Host "❌ Failed to find OpenSSL installation"
            exit 1
          }
          
          # Create junction to C:\OpenSSL-Win64 if needed
          if ($ACTUAL_OPENSSL_DIR -ne "C:\OpenSSL-Win64") {
            if (-not (Test-Path "C:\OpenSSL-Win64")) {
              Write-Host "Creating junction from C:\OpenSSL-Win64 to $ACTUAL_OPENSSL_DIR"
              New-Item -ItemType Junction -Path "C:\OpenSSL-Win64" -Target $ACTUAL_OPENSSL_DIR -Force | Out-Null
              Write-Host "✅ Junction created"
            }
          }
          
          Write-Host "✅ OpenSSL ready"

      - name: Set up environment variables
        shell: powershell
        run: |
          # Set OpenSSL directory (64-bit)
          $OPENSSL_DIR = "C:\OpenSSL-Win64"
          
          if (-not (Test-Path "$OPENSSL_DIR")) {
            Write-Host "❌ OpenSSL directory not found: $OPENSSL_DIR"
            exit 1
          }
          
          # Find lib directory structure
          if (Test-Path "$OPENSSL_DIR/lib/VC/x64/MD") {
            $LIB_PATH = "$OPENSSL_DIR/lib/VC/x64/MD"
          } elseif (Test-Path "$OPENSSL_DIR/lib/VC") {
            $LIB_PATH = "$OPENSSL_DIR/lib/VC"
          } elseif (Test-Path "$OPENSSL_DIR/lib") {
            $LIB_PATH = "$OPENSSL_DIR/lib"
          } else {
            Write-Host "❌ OpenSSL lib directory not found!"
            exit 1
          }
          
          Write-Host "✅ Using OpenSSL lib path: $LIB_PATH"
          
          # Set environment variables
          echo "OPENSSL_DIR=$OPENSSL_DIR" >> $env:GITHUB_ENV
          echo "CGO_CFLAGS=-I$OPENSSL_DIR/include" >> $env:GITHUB_ENV
          echo "CGO_LDFLAGS=-L$LIB_PATH -lssl -lcrypto -lws2_32 -lcrypt32" >> $env:GITHUB_ENV
          
          # Add to PATH
          echo "$OPENSSL_DIR/bin" >> $env:GITHUB_PATH
          echo "C:/Program Files/wkhtmltopdf/bin" >> $env:GITHUB_PATH

      - name: Install Go dependencies
        run: |
          go mod download
          go mod tidy

      - name: Build GUI for Windows
        shell: powershell
        run: |
          $env:CGO_ENABLED = "1"
          go build -ldflags="-s -w -H windowsgui" -o build/ravro_dcrpt_gui.exe ./cmd/gui

      - name: Copy runtime DLLs
        shell: powershell
        run: |
          # Create build directory if not exists
          New-Item -ItemType Directory -Force -Path build
          
          # Copy OpenSSL DLLs (64-bit)
          $OPENSSL_BIN = "C:\OpenSSL-Win64\bin"
          if (Test-Path "$OPENSSL_BIN\libssl-3-x64.dll") {
            Copy-Item "$OPENSSL_BIN\libssl-3-x64.dll" build/
            Copy-Item "$OPENSSL_BIN\libcrypto-3-x64.dll" build/
            Write-Host "✅ Copied OpenSSL DLLs"
          } elseif (Test-Path "$OPENSSL_BIN\libssl-3.dll") {
            Copy-Item "$OPENSSL_BIN\libssl-3.dll" build/
            Copy-Item "$OPENSSL_BIN\libcrypto-3.dll" build/
            Write-Host "✅ Copied OpenSSL DLLs"
          } else {
            Write-Host "⚠️ OpenSSL DLLs not found"
          }
          
          # Copy any local DLLs from lib/ if they exist
          if (Test-Path "lib\*.dll") {
            Copy-Item lib\*.dll build\
          }

      - name: Create zip archive
        shell: powershell
        run: |
          # Include all files in build directory
          $files = @("build\ravro_dcrpt_gui.exe")
          if (Test-Path "build\*.dll") {
            $files += Get-ChildItem "build\*.dll" | ForEach-Object { $_.FullName }
          }
          
          Compress-Archive -Path $files -DestinationPath "build\ravro_dcrpt-windows-amd64.zip" -Force

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-amd64
          path: build/ravro_dcrpt-windows-amd64.zip
          retention-days: 7

  create-release:
    name: Create GitHub Release
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/linux-amd64/*.tar.gz
            artifacts/macos-amd64/*.tar.gz
            artifacts/macos-arm64/*.tar.gz
            artifacts/windows-amd64/*.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

