name: CI - Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-quick-linux:
    name: Quick Build (Linux)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc \
            libgl1-mesa-dev \
            xorg-dev \
            libx11-dev \
            libxcursor-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxi-dev \
            libssl-dev \
            pkg-config

      - name: Install Go dependencies
        run: |
          go mod download

      - name: Build GUI
        run: |
          CGO_ENABLED=1 go build -o build/ravro_dcrpt_gui ./cmd/gui

      - name: Verify GUI binary exists
        run: |
          ls -lh build/ravro_dcrpt_gui

  build-quick-macos:
    name: Quick Build (macOS)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-13
            arch: amd64
          - os: macos-latest
            arch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Install macOS dependencies
        run: |
          # Install OpenSSL
          if ! brew list openssl@3 &>/dev/null; then
            brew install openssl@3
          else
            echo "OpenSSL@3 is already installed"
          fi

      - name: Set OpenSSL environment (Intel)
        if: matrix.arch == 'amd64'
        run: |
          OPENSSL_PREFIX="/usr/local/opt/openssl@3"
          echo "PKG_CONFIG_PATH=$OPENSSL_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "CGO_CFLAGS=-I$OPENSSL_PREFIX/include" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-L$OPENSSL_PREFIX/lib -lssl -lcrypto" >> $GITHUB_ENV

      - name: Set OpenSSL environment (Apple Silicon)
        if: matrix.arch == 'arm64'
        run: |
          OPENSSL_PREFIX="/opt/homebrew/opt/openssl@3"
          echo "PKG_CONFIG_PATH=$OPENSSL_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "CGO_CFLAGS=-I$OPENSSL_PREFIX/include" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-L$OPENSSL_PREFIX/lib -lssl -lcrypto" >> $GITHUB_ENV

      - name: Install Go dependencies
        run: |
          go mod download

      - name: Build GUI
        run: |
          CGO_ENABLED=1 go build -o build/ravro_dcrpt_gui-${{ matrix.arch }} ./cmd/gui

      - name: Verify GUI binary exists
        run: |
          ls -lh build/ravro_dcrpt_gui-${{ matrix.arch }}

  build-quick-windows:
    name: Quick Build (Windows) (${{ matrix.arch }})
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - arch: amd64
            goarch: amd64
            mingw: mingw64
            openssl_url_prefix: Win64OpenSSL
            openssl_dir: C:\OpenSSL-Win64
          - arch: 386
            goarch: 386
            mingw: mingw32
            openssl_url_prefix: Win32OpenSSL
            openssl_dir: C:\OpenSSL-Win32
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Install MinGW for ${{ matrix.arch }}
        shell: powershell
        run: |
          if ("${{ matrix.arch }}" -eq "386") {
            Write-Host "Installing MinGW 32-bit..."
            choco install -y mingw --forcex86 --force
            
            # Verify installation
            if (Test-Path "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw32") {
              Write-Host "✅ MinGW 32-bit installed"
              echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw32\bin" >> $env:GITHUB_PATH
            } else {
              Write-Host "❌ MinGW 32-bit installation failed"
              exit 1
            }
          } else {
            Write-Host "Using default MinGW 64-bit"
            # MinGW 64-bit is usually pre-installed
          }

      - name: Install Windows dependencies
        shell: powershell
        run: |
          # Install wkhtmltopdf
          choco install -y wkhtmltopdf
          
          # Install OpenSSL via chocolatey (more reliable)
          Write-Host "Installing OpenSSL via Chocolatey..."
          
          if ("${{ matrix.arch }}" -eq "386") {
            # For 32-bit, we need to use a different approach
            Write-Host "Installing OpenSSL (will install 64-bit, but we'll handle libs separately)..."
            choco install -y openssl
            
            # Try to find and setup 32-bit libs
            # Note: Windows OpenSSL from chocolatey typically installs 64-bit
            # For 32-bit builds, we may need to compile or use pre-built libs
            Write-Host "⚠️ Note: 32-bit OpenSSL may require manual library setup"
          } else {
            # For 64-bit, straightforward chocolatey install
            choco install -y openssl
          }
          
          # Check common installation paths
          $OPENSSL_PATHS = @(
            "C:\Program Files\OpenSSL-Win64",
            "C:\Program Files\OpenSSL",
            "C:\OpenSSL-Win64",
            "C:\OpenSSL"
          )
          
          $OPENSSL_FOUND = $false
          $ACTUAL_OPENSSL_DIR = ""
          
          foreach ($path in $OPENSSL_PATHS) {
            if (Test-Path $path) {
              Write-Host "✅ Found OpenSSL at: $path"
              $ACTUAL_OPENSSL_DIR = $path
              $OPENSSL_FOUND = $true
              break
            }
          }
          
          if (-not $OPENSSL_FOUND) {
            Write-Host "❌ OpenSSL not found in common locations"
            Write-Host "Searching for OpenSSL..."
            
            # Search in Program Files
            $found = Get-ChildItem "C:\Program Files" -Directory -Filter "*OpenSSL*" -ErrorAction SilentlyContinue | Select-Object -First 1
            if ($found) {
              $ACTUAL_OPENSSL_DIR = $found.FullName
              Write-Host "✅ Found OpenSSL at: $ACTUAL_OPENSSL_DIR"
              $OPENSSL_FOUND = $true
            }
          }
          
          if (-not $OPENSSL_FOUND) {
            Write-Host "❌ Failed to find OpenSSL installation"
            exit 1
          }
          
          # Create symlink/junction to expected location if needed
          if ($ACTUAL_OPENSSL_DIR -ne "${{ matrix.openssl_dir }}") {
            if (-not (Test-Path "${{ matrix.openssl_dir }}")) {
              Write-Host "Creating junction from ${{ matrix.openssl_dir }} to $ACTUAL_OPENSSL_DIR"
              New-Item -ItemType Junction -Path "${{ matrix.openssl_dir }}" -Target $ACTUAL_OPENSSL_DIR -Force | Out-Null
              Write-Host "✅ Junction created"
            }
          }
          
          # Verify installation
          if (Test-Path "${{ matrix.openssl_dir }}") {
            Write-Host "✅ OpenSSL ready at ${{ matrix.openssl_dir }}"
            Get-ChildItem "${{ matrix.openssl_dir }}" | Select-Object Name
          } else {
            Write-Host "❌ OpenSSL setup failed"
            exit 1
          }

      - name: Set up environment variables
        shell: powershell
        run: |
          # Set OpenSSL directory
          $OPENSSL_DIR = "${{ matrix.openssl_dir }}"
          
          if (-not (Test-Path "$OPENSSL_DIR")) {
            Write-Host "❌ OpenSSL directory not found: $OPENSSL_DIR"
            exit 1
          }
          
          Write-Host "✅ Found OpenSSL at: $OPENSSL_DIR"
          
          # Find lib directory structure based on architecture
          if ("${{ matrix.arch }}" -eq "386") {
            # For 32-bit, look for x86 libraries
            if (Test-Path "$OPENSSL_DIR/lib/VC/x86/MD") {
              $LIB_PATH = "$OPENSSL_DIR/lib/VC/x86/MD"
              Write-Host "✅ Using VC x86 lib path: $LIB_PATH"
            } elseif (Test-Path "$OPENSSL_DIR/lib/VC") {
              $LIB_PATH = "$OPENSSL_DIR/lib/VC"
              Write-Host "✅ Using VC lib path: $LIB_PATH"
            } elseif (Test-Path "$OPENSSL_DIR/lib") {
              $LIB_PATH = "$OPENSSL_DIR/lib"
              Write-Host "✅ Using standard lib path: $LIB_PATH"
            } else {
              Write-Host "❌ OpenSSL lib directory not found!"
              Write-Host "Directory contents:"
              Get-ChildItem -Path $OPENSSL_DIR -Recurse -Depth 2 | Select-Object FullName
              exit 1
            }
          } else {
            # For 64-bit, look for x64 libraries
            if (Test-Path "$OPENSSL_DIR/lib/VC/x64/MD") {
              $LIB_PATH = "$OPENSSL_DIR/lib/VC/x64/MD"
              Write-Host "✅ Using VC x64 lib path: $LIB_PATH"
            } elseif (Test-Path "$OPENSSL_DIR/lib/VC") {
              $LIB_PATH = "$OPENSSL_DIR/lib/VC"
              Write-Host "✅ Using VC lib path: $LIB_PATH"
            } elseif (Test-Path "$OPENSSL_DIR/lib") {
              $LIB_PATH = "$OPENSSL_DIR/lib"
              Write-Host "✅ Using standard lib path: $LIB_PATH"
            } else {
              Write-Host "❌ OpenSSL lib directory not found!"
              Write-Host "Directory contents:"
              Get-ChildItem -Path $OPENSSL_DIR -Recurse -Depth 2 | Select-Object FullName
              exit 1
            }
          }
          
          # Verify include directory
          if (-not (Test-Path "$OPENSSL_DIR/include/openssl")) {
            Write-Host "❌ OpenSSL include directory not found!"
            exit 1
          }
          Write-Host "✅ Found OpenSSL headers at: $OPENSSL_DIR/include"
          
          # Set environment variables
          echo "OPENSSL_DIR=$OPENSSL_DIR" >> $env:GITHUB_ENV
          echo "CGO_CFLAGS=-I$OPENSSL_DIR/include" >> $env:GITHUB_ENV
          echo "CGO_LDFLAGS=-L$LIB_PATH -lssl -lcrypto -lws2_32 -lcrypt32" >> $env:GITHUB_ENV
          echo "GOARCH=${{ matrix.goarch }}" >> $env:GITHUB_ENV
          
          # Add to PATH
          echo "$OPENSSL_DIR/bin" >> $env:GITHUB_PATH
          echo "C:/Program Files/wkhtmltopdf/bin" >> $env:GITHUB_PATH
          
          Write-Host "`n=== Environment Configuration ==="
          Write-Host "Architecture: ${{ matrix.arch }}"
          Write-Host "GOARCH: ${{ matrix.goarch }}"
          Write-Host "OPENSSL_DIR: $OPENSSL_DIR"
          Write-Host "CGO_CFLAGS: -I$OPENSSL_DIR/include"
          Write-Host "CGO_LDFLAGS: -L$LIB_PATH -lssl -lcrypto -lws2_32 -lcrypt32"

      - name: Install Go dependencies
        run: |
          go mod download

      - name: Build GUI
        shell: powershell
        run: |
          $env:CGO_ENABLED = "1"
          $env:GOOS = "windows"
          $env:GOARCH = "${{ matrix.goarch }}"
          
          if ("${{ matrix.arch }}" -eq "386") {
            $OUTPUT_NAME = "build/ravro_dcrpt_gui-386.exe"
          } else {
            $OUTPUT_NAME = "build/ravro_dcrpt_gui.exe"
          }
          
          go build -o $OUTPUT_NAME ./cmd/gui

      - name: Verify GUI binary exists
        shell: powershell
        run: |
          if ("${{ matrix.arch }}" -eq "386") {
            Get-ChildItem build/ravro_dcrpt_gui-386.exe
          } else {
            Get-ChildItem build/ravro_dcrpt_gui.exe
          }

