name: CI - Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-quick-linux:
    name: Quick Build (Linux)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc \
            libgl1-mesa-dev \
            xorg-dev \
            libx11-dev \
            libxcursor-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxi-dev \
            libssl-dev \
            pkg-config

      - name: Install Go dependencies
        run: |
          go mod download

      - name: Build GUI
        run: |
          CGO_ENABLED=1 go build -o build/ravro_dcrpt_gui ./cmd/gui

      - name: Verify GUI binary exists
        run: |
          ls -lh build/ravro_dcrpt_gui

  build-quick-macos:
    name: Quick Build (macOS)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-13
            arch: amd64
          - os: macos-latest
            arch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Install macOS dependencies
        run: |
          # Install OpenSSL
          if ! brew list openssl@3 &>/dev/null; then
            brew install openssl@3
          else
            echo "OpenSSL@3 is already installed"
          fi

      - name: Set OpenSSL environment (Intel)
        if: matrix.arch == 'amd64'
        run: |
          OPENSSL_PREFIX="/usr/local/opt/openssl@3"
          echo "PKG_CONFIG_PATH=$OPENSSL_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "CGO_CFLAGS=-I$OPENSSL_PREFIX/include" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-L$OPENSSL_PREFIX/lib -lssl -lcrypto" >> $GITHUB_ENV

      - name: Set OpenSSL environment (Apple Silicon)
        if: matrix.arch == 'arm64'
        run: |
          OPENSSL_PREFIX="/opt/homebrew/opt/openssl@3"
          echo "PKG_CONFIG_PATH=$OPENSSL_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "CGO_CFLAGS=-I$OPENSSL_PREFIX/include" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-L$OPENSSL_PREFIX/lib -lssl -lcrypto" >> $GITHUB_ENV

      - name: Install Go dependencies
        run: |
          go mod download

      - name: Build GUI
        run: |
          CGO_ENABLED=1 go build -o build/ravro_dcrpt_gui-${{ matrix.arch }} ./cmd/gui

      - name: Verify GUI binary exists
        run: |
          ls -lh build/ravro_dcrpt_gui-${{ matrix.arch }}

  build-quick-windows:
    name: Quick Build (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Install Windows dependencies
        shell: powershell
        run: |
          # Install wkhtmltopdf
          choco install -y wkhtmltopdf
          
          # Install OpenSSL (64-bit only)
          Write-Host "Installing OpenSSL via Chocolatey..."
          choco install -y openssl
          
          # Check common installation paths
          $OPENSSL_PATHS = @(
            "C:\Program Files\OpenSSL-Win64",
            "C:\Program Files\OpenSSL",
            "C:\OpenSSL-Win64",
            "C:\OpenSSL"
          )
          
          $OPENSSL_FOUND = $false
          $ACTUAL_OPENSSL_DIR = ""
          
          foreach ($path in $OPENSSL_PATHS) {
            if (Test-Path $path) {
              Write-Host "✅ Found OpenSSL at: $path"
              $ACTUAL_OPENSSL_DIR = $path
              $OPENSSL_FOUND = $true
              break
            }
          }
          
          if (-not $OPENSSL_FOUND) {
            Write-Host "Searching for OpenSSL in Program Files..."
            $found = Get-ChildItem "C:\Program Files" -Directory -Filter "*OpenSSL*" -ErrorAction SilentlyContinue | Select-Object -First 1
            if ($found) {
              $ACTUAL_OPENSSL_DIR = $found.FullName
              Write-Host "✅ Found OpenSSL at: $ACTUAL_OPENSSL_DIR"
              $OPENSSL_FOUND = $true
            }
          }
          
          if (-not $OPENSSL_FOUND) {
            Write-Host "❌ Failed to find OpenSSL installation"
            exit 1
          }
          
          # Create junction to C:\OpenSSL-Win64 if needed
          if ($ACTUAL_OPENSSL_DIR -ne "C:\OpenSSL-Win64") {
            if (-not (Test-Path "C:\OpenSSL-Win64")) {
              Write-Host "Creating junction from C:\OpenSSL-Win64 to $ACTUAL_OPENSSL_DIR"
              New-Item -ItemType Junction -Path "C:\OpenSSL-Win64" -Target $ACTUAL_OPENSSL_DIR -Force | Out-Null
              Write-Host "✅ Junction created"
            }
          }
          
          Write-Host "✅ OpenSSL ready"

      - name: Set up environment variables
        shell: powershell
        run: |
          # Set OpenSSL directory (64-bit)
          $OPENSSL_DIR = "C:\OpenSSL-Win64"
          
          if (-not (Test-Path "$OPENSSL_DIR")) {
            Write-Host "❌ OpenSSL directory not found: $OPENSSL_DIR"
            exit 1
          }
          
          # Find lib directory structure
          if (Test-Path "$OPENSSL_DIR/lib/VC/x64/MD") {
            $LIB_PATH = "$OPENSSL_DIR/lib/VC/x64/MD"
          } elseif (Test-Path "$OPENSSL_DIR/lib/VC") {
            $LIB_PATH = "$OPENSSL_DIR/lib/VC"
          } elseif (Test-Path "$OPENSSL_DIR/lib") {
            $LIB_PATH = "$OPENSSL_DIR/lib"
          } else {
            Write-Host "❌ OpenSSL lib directory not found!"
            exit 1
          }
          
          Write-Host "✅ Using OpenSSL lib path: $LIB_PATH"
          
          # Set environment variables
          echo "OPENSSL_DIR=$OPENSSL_DIR" >> $env:GITHUB_ENV
          echo "CGO_CFLAGS=-I$OPENSSL_DIR/include" >> $env:GITHUB_ENV
          echo "CGO_LDFLAGS=-L$LIB_PATH -lssl -lcrypto -lws2_32 -lcrypt32" >> $env:GITHUB_ENV
          
          # Add to PATH
          echo "$OPENSSL_DIR/bin" >> $env:GITHUB_PATH
          echo "C:/Program Files/wkhtmltopdf/bin" >> $env:GITHUB_PATH

      - name: Install Go dependencies
        run: |
          go mod download

      - name: Build GUI
        shell: powershell
        run: |
          $env:CGO_ENABLED = "1"
          go build -o build/ravro_dcrpt_gui.exe ./cmd/gui

      - name: Verify GUI binary exists
        shell: powershell
        run: |
          Get-ChildItem build/ravro_dcrpt_gui.exe

