name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          checkinstall \
          zlib1g-dev \
          openssl \
          libssl-dev \
          unzip \
          wget \
          fontconfig \
          libfreetype6 \
          libx11-dev \
          libxext-dev \
          libxrender-dev \
          xfonts-base \
          xfonts-75dpi

    - name: Download and Install wkhtmltopdf
      run: |
        wget https://downloads.wkhtmltopdf.org/0.12.6/wkhtmltox_0.12.6-1.bionic_amd64.deb
        sudo dpkg -i wkhtmltox_0.12.6-1.bionic_amd64.deb || true
        sudo apt-get install -f -y
        sudo ldconfig

    - name: Verify wkhtmltopdf Installation
      run: |
        ls -l /usr/include/wkhtmltox
        ls -l /usr/lib

    - name: Cleanup
      run: |
        rm wkhtmltox_0.12.6-1.bionic_amd64.deb

    - name: Build
      env:
        CGO_ENABLED: 1
        CGO_CFLAGS: "-I/usr/include/wkhtmltox"
        CGO_LDFLAGS: "-L/usr/lib -lwkhtmltox"
      run: |
        go build -v -tags static -ldflags '-extldflags "-static"' ./...

    - name: Test
      env:
        CGO_ENABLED: 1
        CGO_CFLAGS: "-I/usr/include/wkhtmltox"
        CGO_LDFLAGS: "-L/usr/lib -lwkhtmltox"
      run: go test -v ./...
