name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install wkhtmltopdf
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
        sudo dpkg -i wkhtmltox_0.12.6-1.focal_amd64.deb
        sudo apt-get install -f

    - name: Install dependencies
      run: |
        sudo apt-get install -y libssl-dev

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
