name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install Dependencies and Setup
      run: |
        set -e
        echo "[+++] Updating package lists and installing dependencies..."
        sudo apt update && sudo apt install -y build-essential checkinstall zlib1g-dev openssl libssl-dev unzip wget
        
        echo "[+++] Downloading wkhtmltox..."
        wget -q https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.bullseye_amd64.deb
        
        echo "[+++] Installing wkhtmltox..."
        sudo dpkg -i wkhtmltox_0.12.6.1-2.bullseye_amd64.deb
        sudo apt-get install -f -y
        sudo ldconfig
        echo "[+++] Installation complete!"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
